name: Release

on:
  push:
    branches:
      - "v*"
      - "latest"
permissions:
  contents: write
jobs:
  release:
    runs-on: self-hosted
    strategy:
      matrix:
        goosarch:
          - linux/amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24.1'
      - name: Get OS and arch information
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          APP_NAME=dsp
          BINARY_NAME=${APP_NAME}-$GOOS-$GOARCH-${{github.ref_name}}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build binary
        run: |
          go build -o $BINARY_NAME ./main.go
      - name: Create Release note
        run:
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Release binary
        uses: softprops/action-gh-release@v2.2.1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: false
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}