name: Release

on:
  push:
    branches:
      - main
    # tags:
    #   - "v*"

jobs:
  release:
    runs-on: archlinux
    strategy:
      matrix:
        goosarch:
          - linux/amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.24.1'
      - name: Get OS and arch information
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build binary
        run: |
          go build -o $BINARY_NAME ./main.go
      - name: Create Release note
        run:
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * %an <%ae>' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Release binary
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          draft: true
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}